### ISSUE TITLE
Web app: Allow switch accounts and not just sign out

### ISSUE THREAD

**Issue by kyliedonia** [doug-m/field-maps-testing#11]
### Is your feature request related to a problem? Please describe.
Most places in ArcGIS Online I can switch account to change which identity I'm using. This is great and saves a lot of password typing and has them linked. Clicking "sign out" sometimes has affects on the accounts that are linked and propagates through other places where that account is in use. As a result, I'm skeptical of the sign out button and always prefer to just switch to the account I need.

### Describe the solution you'd like
Allow switch next to sign out in the menu.

### Describe alternatives you've considered

**Additional context**

**Comment by crai3162** [comment]
thanks for the request @kyliedonia we don't have any plans to support this in the Field Maps web app until it's part of a larger initiative to support it in all esri web apps.  We'll keep it in mind for discussions with the other teams but as of now, there aren't any plans for this.
