### ISSUE TITLE
Web app: Make it easier to work with Field Maps and ArcGIS Online simultaneously 

### ISSUE THREAD

**Issue by kyliedonia** [doug-m/field-maps-testing#12]
### Is your feature request related to a problem? Please describe.
What you can do in the Field Maps web app is limited for authoring maps -- you can work with the form, offline experience, layer properties, and a few other things. But you can't create the map or the layers (even from a template) so you really need to still use ArcGIS Online (or ArcGIS Enterprise) alongside ArcGIS Field Maps. I found I was switching between them, and wanted two things to make that smoother:

1. The ability to easily go from Field Maps to my org content and Map Viewer to make the maps and layers. (For example, a button to go to contents or back to org page or something.)
2. The list of maps in Field Maps to refresh when I've added a new map. 

### Describe alternatives you've considered

**Additional context**

**Comment by crai3162** [comment]
thanks for the feedback @kyliedonia 
1. This is in our plans and may be there for the initial release
2. No plans for this; you'll need to manually refresh the app to pick up new web maps that are added in Online outside of Field Maps.
