### ISSUE TITLE
Stale tool notification on FieldMaps WebApp

### ISSUE THREAD

**Issue by ahnam** [doug-m/field-maps-testing#15]
### Issue
If I delete a template on a later, the 'Delete' tool notification remains
### Expected Behavior
 After deleting a template, the 'Delete' notification should no longer be visible.

### Steps to Reproduce
From web app, choose a map to create template for
choose editable layer
Duplicate a template that is already existing
delete the duplicate template
Note that the 'Delete' notice is still present

#### Browser (please complete the following information):
 - Browser: Chrome 
 - Version :  85.0.4183.102

### Screenshots
![image](https://user-images.githubusercontent.com/22575193/94067767-32ae4600-fda3-11ea-8f20-99629aed921c.png)

![image](https://user-images.githubusercontent.com/22575193/94067922-5f625d80-fda3-11ea-8404-70d38d6fe230.png)

**Comment by crai3162** [comment]
Hi @ahnam thanks for reporting it; this is a known issue in the beta and something we're looking at addressing for final.
