### ISSUE TITLE
Web APP: As an AGOL Administrator I am unable to view any other maps than my own

### ISSUE THREAD

**Issue by AmandaHuber** [doug-m/field-maps-testing#2]
### Issue
As an AGOL Administrator I am unable to view any other maps than my own

### Expected Behavior
As an organization administrator I should be able to see all my content  _and_ my user's content and I cannot in the web interface. 

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce
No other content visable

#### Browser (please complete the following information):
 - Browser Chrome
 - Version 85.0.4183.83 (Official Build) (64-bit)

#### Mobile (please complete the following information):
NA

### Screenshots
![image](https://user-images.githubusercontent.com/62111701/94039300-27502000-fd8d-11ea-8c4a-4956144299fa.png)

**Comment by kyliedonia** [comment]
To add to this, I'd also expect content shared with me through a group with collaboration allowed to also be available.

**Comment by AmandaHuber** [comment]
I also agree to that ^

**Comment by crai3162** [comment]
Hi @AmandaHuber thanks for this feedback.  Some questions:

1. What tasks would you expect to be able to perform on the web maps owned by other users in your organization?
  a. Manage Sharing
  b. Configure Offline
  c. Manage Templates
  d. Author Forms
2. If all web maps in your organization were included; how should they appear on the browse screen? Should they appear alongside your maps?  Should they be in a separate location or denoted somehow?

thanks, Craig

**Comment by crai3162** [comment]
@AmandaHuber @kyliedonia on the question of :
> To add to this, I'd also expect content shared with me through a group with collaboration allowed to also be available.

Does your named user own the web maps in these groups?  Or, is does this request follow-on to the question of:
> As an AGOL Administrator I am unable to view any other maps than my own

thanks

**Comment by kyliedonia** [comment]
The maps shared with a collaborative group and owned by the signed-in user are available in "My Maps." I'd expect that the maps owned by others and shared collaboratively to be available, too. My train of thought was that the Field Maps app is for managing/editing maps, and I am allowed to edit maps I don't own if they are shared with a collaborative group, and I'd want to make use of this tool for those shared maps.

**Comment by crai3162** [comment]
got it, thanks @kyliedonia .

Yes, this is something we're looking at but may not make the first release.

**Comment by AmandaHuber** [comment]
Hi Craig, 
Great questions! 
_What tasks would you expect to be able to perform on the web maps owned by other users in your organization?_
I would expect all of the above tasks to be available to an admin as many times users either need maps/content prepared for them or items troubleshooted. 

_If all web maps in your organization were included; how should they appear on the browse screen? Should they appear alongside your maps? Should they be in a separate location or denoted somehow?_
I think the best way to accomplish this would be how ArcGIS Dashboards or Quick Capture handle this with tabs for "My Content" and "Shared Content"
![image](https://user-images.githubusercontent.com/62111701/94060932-545efb80-fdaa-11ea-9c63-5f79a6889031.png)
![image](https://user-images.githubusercontent.com/62111701/94060961-5d4fcd00-fdaa-11ea-9cdd-c9c88d97b2fd.png)

**Comment by crai3162** [comment]
Hi @AmandaHuber thanks for the info; it's exactly what we're looking for.

This probably will not make the first release for Field Maps web (which is December) but I've got it in our backlog to consider.
