### ISSUE TITLE
Field Maps Web - Ability to sort by Date Modified (least/most recent) and Title

### ISSUE THREAD

**Issue by AmandaHuber** [doug-m/field-maps-testing#22]
### Is your feature request related to a problem? Please describe.
There needs to be a way to filter or sort the laundry list of maps in the Field Map web by the Date Modified (least/most recent) and Title.

### Describe the solution you'd like
I'd like the same options that are presented in a variety of other Esri products- 
![image](https://user-images.githubusercontent.com/62111701/94167980-c1c66700-fe52-11ea-8346-0c0d467f323d.png)
![image](https://user-images.githubusercontent.com/62111701/94168029-d3a80a00-fe52-11ea-85ed-9b3fb6a8be94.png)

### Describe alternatives you've considered
NA

**Additional context**
![image](https://user-images.githubusercontent.com/62111701/94168124-ede1e800-fe52-11ea-8dc8-b50cc130fa6a.png)

**Comment by crai3162** [comment]
hey @AmandaHuber thanks for posting this.

We have this in our backlog to consider adding - undetermined if this will be in the first release though.

**Comment by AmandaHuber** [comment]
Thanks for the update, that's great to hear!
