### ISSUE TITLE
Field Maps Web- Ability to Edit the web map from this interface

### ISSUE THREAD

**Issue by AmandaHuber** [doug-m/field-maps-testing#23]
### Is your feature request related to a problem? Please describe.
Currently there is no direct way from the Field Maps Web to edit an existing map. Currently users need to find the map they want in field maps > realize they need to edit the map/ make changes/ or add layers > go to AGOL page > find the map> update the map. 

### Describe the solution you'd like
A simple "Edit Web Map" button/option would resolve this limitation or one step better a map editor built into the site like WAB has would be great: 
![image](https://user-images.githubusercontent.com/62111701/94168880-b7f13380-fe53-11ea-9cb0-9c399e8165e9.png)

### Describe alternatives you've considered

**Additional context**
![image](https://user-images.githubusercontent.com/62111701/94168490-4fa25200-fe53-11ea-8da8-fbb22a59c49d.png)

**Comment by crai3162** [comment]
@AmandaHuber this is also in our backlog to add.  We'll have this on the Overview tab.

**Comment by AmandaHuber** [comment]
Again great to hear, thanks!
