### ISSUE TITLE
Field Maps Web- Map owned by me (and is editable) but missing from Web interface

### ISSUE THREAD

**Issue by AmandaHuber** [doug-m/field-maps-testing#25]
### Issue
Please see screenshots below- Map owned by me (and is editable) but missing from Web interface

### Expected Behavior
Map to be visible in the Field Maps Web interface

### Map and Credentials

* Group Name: Field Maps Holistic
* Map Name: Regional Trail Incidents MAP

### Steps to Reproduce
Unable to find or open

### Device Information
Chrome

#### Browser (please complete the following information):
 - Browser Chrome
 - Version  85.0.4183.83 (Official Build) (64-bit)

#### Mobile (please complete the following information):
NA

### Screenshots

![image](https://user-images.githubusercontent.com/62111701/94172714-731bcb80-fe58-11ea-9d6b-9c5b913dfa38.png)

Editable: 
![image](https://user-images.githubusercontent.com/62111701/94172744-7e6ef700-fe58-11ea-85f3-4c457d8fc9fb.png)

Owned by me: 
![image](https://user-images.githubusercontent.com/62111701/94172801-921a5d80-fe58-11ea-8871-2027ab7e984c.png)

**Comment by crai3162** [comment]
Hi @AmandaHuber the map has the `CollectorDisabled` keyword; you can change this at the bottom of the Settings tab in the map item details page.

Having said that; we're changing this experience in the release next week and this map will be available to use.  You'll see a preview of it in the wrap up today.
