### ISSUE TITLE
No Warning for Basemap Coordinate System

### ISSUE THREAD

**Issue by BrettFrahm** [doug-m/field-maps-testing#3]
@AmandaHuber

### Issue
I have a web map with a NAD 1983 UTM 15N basemap and with a Location Profile set on default(using GCS WGS 1984), the web works. The web map should not let you open because the location profile coordinate system does not match the basemap.

### Expected Behavior
App should warn me and not let me use a map where coordinate system does not match

### Map and Credentials
* Group Name: Field Maps Holistic - Three Rivers Park District
* Map Name:  [Collector - Trail Collection](https://trpd.maps.arcgis.com/home/item.html?id=e953b371b3fe437d9de916e60a3c3ad8)

### Steps to Reproduce
Location profile:
- Set to "GCS NAD 1983 2011" (6318)  

- Set to "NAD 1983 2011 UTM 15N" (26915)   

- Ex: WGS1984_(ITRF08)_To_NAD_1983_2011 + WGS_1984_(ITRF00)_To_NAD_1983

#### Mobile (please complete the following information):
 - Device: iPhone 11 Pro
 - OS: 13.3.1

### Additional context
On a web map with GCS WGS 1984 base and with a location profile set to using NAD 1983 UTM 15N, the webmap does properly warn me that the coordinate systems do not match.

**Comment by miaogeng** [comment]
@BrettFrahm Using Default profile, it doesn't limit the webmap coordinate system choice. It will assume location from device is at GCS WGS 1984 (no webmap coordinate system) and we will automatically pick the transformation and project into webmap coordinate system. The warning will only show when you define your own location profile.
