### ISSUE TITLE
Custom fields in Locators do not show up in Field Maps App

### ISSUE THREAD

**Issue by geotrek** [doug-m/field-maps-testing#33]
### Issue
Custom fields in Locators do not show up in Field Maps App
### Expected Behavior
Define custom fields in locators in PRO and map them using the Create Locator Geoprocessing Tool. Fields show up in PRO but not when searching in Field Maps.

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce
See Geonet [post](https://tinyurl.com/y5qh3efo)

#### Browser (please complete the following information):
NA

#### Mobile (please complete the following information):
 - Android 10, Note 10+
 - OS 11

**Comment by CDunn-fm** [comment]
@geotrek we have added this to our product plan for Field Maps.
