### ISSUE TITLE
Web app: Getting back to list of Form Elements and Attributes unintuitive

### ISSUE THREAD

**Issue by kyliedonia** [doug-m/field-maps-testing#35]
### Issue

Once configuring an entry in the form, I was unable to get back to the list of Form Elements and Attributes to add the next one -- until accidentally clicking the selected item got me there. 

### Expected Behavior

There should be a clear way to return to the Form Elements and Attributes lists to keep building the form.

### Steps to Reproduce
1. Edit a form.
2. Select one of the entries already in place in the form to access its properties (like formatting). 
3. Change the formatting.
4. I can't seem to get back to the list of Form Elements and Attributes to continue building the form. I have to click to Templates and then back to Form to get them back and continue with adding items.
   * as I typed this up, I found that you could also click on the selected item to unselect it and get back to the other list - so I already made this as a bug but maybe enhancement would make more sense since it turns out there is a way).

### Device Information
Windows 10 laptop

#### Browser (please complete the following information):
 - Browser [e.g. Chrome, Safari] Chrome
 - Version [e.g. 22] 85.0.4183.121

#### Mobile (please complete the following information):
 - Device: [e.g. iPhone 11]
 - OS: [e.g. iOS 13.1]

**Comment by apulverizer** [comment]
@kyliedonia thanks for reporting. This will be resolved in the update next week. Here's a sneak peak.

![Kapture 2020-09-25 at 09 39 13](https://user-images.githubusercontent.com/2099642/94274054-3365ea00-ff13-11ea-9056-eff105c5c756.gif)

**Comment by kyliedonia** [comment]
Awesome! Thanks Aaron :)
