### ISSUE TITLE
More Frequently Used Maps

### ISSUE THREAD

**Issue by BrettFrahm** [doug-m/field-maps-testing#4]
@AmandaHuber

### Describe the solution you'd like
 In list of maps, it should show more than 1 recently used map. Preferably show last 2-5 used web maps. Or at least provide option to favorite maps.

### Describe alternatives you've considered
Preferably show last 2-5 used web maps. Or at least provide option to favorite maps.

**Additional context**
a troubleshooting step for the app often requires you to switch to different map and switch back to map you want to use. Very annoying to have to search each time.

**Comment by Kevin-GIS** [comment]
@BrettFrahm 

In Field Maps when browsing for maps, on the map card itself if you tap on the ellipsis button (three dots) to the far right there is an option for `Add to Favorites`. 

If you haven't already, please test out this functionality and let me know if you have any questions.

Thank you.
