### ISSUE TITLE
Allow users to name ad-hoc offline areas

### ISSUE THREAD

**Issue by AndrewCroisier** [doug-m/field-maps-testing#40]
### Is your feature request related to a problem? Please describe.
Instead of offline areas being named "Area 1", "Area 2" and so on,  can we allow the users to apply names for the offline areas?

I'm imagining it will be much more useful for the end users to give names to maps that align with arbitrary place names, like "West Springfield" or "Lot 65", etc

I understand that administrators can configure this for pre-defined offline areas, but it doesn't seem like the users can name offline areas when adding a new offline area in the mobile device.

**Comment by doug-m** [comment]
@AndrewCroisier you can rename an existing on-demand offline area once downloaded.  For a given area, you tap on the menu, and `Rename Area`.

Note this is also available for Collector and Explorer.

**Comment by AndrewCroisier** [comment]
@doug-m  That's great to hear!

**Comment by Kevin-GIS** [comment]
Closing this one out.
