### ISSUE TITLE
Allow organizations to 'opt-in' rather than 'opt-out'  of default for sharing new maps with Field Maps

### ISSUE THREAD

**Issue by allison-muise** [doug-m/field-maps-testing#42]
### Is your feature request related to a problem? Please describe.
The majority of the web maps I create for my customers are not going to be used in the Field Maps app. They are for Dashboards, Storymaps, Web AppBuilder apps, etc. Most of them will end up shared with groups that may, at some point, include a user account that also has access to the Field Maps app. 

In order to keep the Field Maps apps focused for those users so that they don't have to wade through dozens of maps, I will need to hide all of these maps from the Field Maps app. 

If it was an opt-in workflow, I would only need to think about this setting for the few maps that will be used in Field Maps, rather than needing to adjust it for the many maps I create that will not be used in Field Maps

### Describe the solution you'd like
Allow organizations to choose if it would make more sense for their organization to choose which maps to hide vs choose which maps to show.

### Describe alternatives you've considered
I think that whichever default you choose, a large number of customers will wish for the other. I also know that nowhere else in the ArcGIS platform is content shared by default - it is always an opt-in, and it's unexpected to me to have to opt-out of sharing in this case.

**Comment by crai3162** [comment]
closing as we've logged this in our repo.
